install:
  - wget http://libsdl.org/release/SDL2-2.0.3.tar.gz -O - | tar xz
  - cd SDL2-2.0.3 && ./configure && make -j && sudo make install && cd ..
  - wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.12.tar.gz -O - | tar xz
  - cd SDL2_ttf-2.0.12 && ./configure && make -j && sudo make install && cd ..
language: c
script: make
compiler:
  - clang
  - gcc
